### ISSUE TITLE
About download weights

### ISSUE THREAD

**Issue by dongfeicui** [PKU-YuanGroup/LanguageBind#17]
Why do I download weights again every time I run inference.py ?

**Comment by LinB203** [comment]
You can change what encoders you want to use [here](https://github.com/PKU-YuanGroup/LanguageBind/blob/main/inference.py#L7).
The default code will download image, video, depth and thermal encoder.
There are some [instructions](https://github.com/PKU-YuanGroup/LanguageBind/blob/main/inference.py#L7) about how to use different branch of LanguageBind if you only use a single modality.
