### ISSUE TITLE
Hashtags and prompts?

### ISSUE THREAD

**Issue by Kamino666** [PKU-YuanGroup/LanguageBind#21]
Thank you for your excellent work!

Will you release the hashtags of the videos and the prompt used by mPLUG-owl and ChatGPT?

**Comment by Kamino666** [comment]
Thank you for your prompt response. However, I still have some questions.

You mentioned in section 4.2 of your paper that you filtered videos without hashtags and some irrelevant words. But in the sample data you provided, many videos do not meet this condition. Here is an example:

```json
  "zki3YQY8uBs": {
    "folder": "coco_vat_test",
    "mplug": "This video demonstrates the step-by-step process of wearing a floral theme ear style for a party look. The model shows how to put on the earrings, which include a floral design, and combines them with other accessories, such as a necklace and bracelet.",
    "polish_mplug": "a model demonstrates the process of wearing a floral theme ear style for a party look. The earrings, featuring a floral design, are shown being put on along with other accessories like a necklace and bracelet.",
    "ofa": [
      " a close up of a person wearing a ring",
      " a woman is putting a ring on her ear",
      " a woman is putting a ring on her ear",
      " a close up of a person with a earring in their ear",
      " a close up of a person with a ear piercing",
      " a woman is holding a ring on her finger",
      " a woman holding a pair of scissors in her hand",
      " a close up of a womans ear with a cluster of diamonds on it"
    ],
    "sound_mplug": "the event is a combination of gentle murmurs and soft clicks as the model carefully puts on the floral theme earrings, elegantly accessorizing with a necklace and bracelet for the party look.",
    "raw": "How To Wear A Floral Theme Ear Style - For The Perfect Party Look!  #shorts"
  },
```
`https://www.youtube.com/watch?v=zki3YQY8uBs`

![screenshot](https://github.com/PKU-YuanGroup/LanguageBind/assets/29254156/f6a0c45b-3b0a-4257-982f-9f56f6895c85)


When I visited this video, I noticed that the author included more hashtags in the description below the video that didn't exist in the title. So, my question is, are you using hashtags that are in the title or are you using hashtags that are in the description?

**Comment by BinZhu-ece** [comment]
Not all video descriptions contain this type of hashtags, so we are using the hashtags in the title!

**Comment by Kamino666** [comment]
I see, thanks for your quick reply!
