### ISSUE TITLE
VIT-H model release

### ISSUE THREAD

**Issue by tikboaHIT** [PKU-YuanGroup/LanguageBind#22]
Great job! When is the release date for the Huge model planned?

**Comment by LinB203** [comment]
Thanks for your attention. 
Conservative estimate, end of this month.

**Comment by LinB203** [comment]
Now! Checking our [model zoo](https://github.com/PKU-YuanGroup/LanguageBind/tree/main?tab=readme-ov-file#-model-zoo).
