### ISSUE TITLE
Can you share the NYU-D dataset you used for evaluation, e.g. how to split the dataset?

### ISSUE THREAD

**Issue by bf-yang** [PKU-YuanGroup/LanguageBind#29]

**Comment by LinB203** [comment]
We have uploaded [here](https://github.com/PKU-YuanGroup/LanguageBind/blob/main/TRAIN_AND_VALIDATE.md#depth).
Please pull the latest code.

**Comment by bf-yang** [comment]
@LinB203 Thanks for your sharing the Depth and Thermal datasets. It seems that it only has val dataset with limited data, could you further share some training data for these datasets? like NYU, LLVIP? Thanks!
