### ISSUE TITLE
how to load LanguageBind/LanguageBind_Video_Huge_V1.5_FT model

### ISSUE THREAD

**Issue by valencebond** [PKU-YuanGroup/LanguageBind#30]
Using LanguageBindVideoTower(video_tower, args=video_tower_cfg, cache_dir='', **kwargs) doesn't work. How do I adjust the CLIPVisionTransformer to fit the LanguageBind_Video_Huge_V1.5_FT model

**Comment by LinB203** [comment]
Hi, refer to our [api](https://github.com/PKU-YuanGroup/LanguageBind?tab=readme-ov-file#video), just replace the model name and it works fine.
```
pretrained_ckpt = 'LanguageBind/LanguageBind_Video_Huge_V1.5_FT'  # also 'LanguageBind/LanguageBind_Video'
```
