### ISSUE TITLE
What is the training configurations for full tuning?

### ISSUE THREAD

**Issue by StanLei52** [PKU-YuanGroup/LanguageBind#32]
Hi, I notice that in your paper, the results for full-tuning are reported. I'd like to know the training configurations for full tuning -- do you use the text prompt and input modality data with contrastive learning during full tuning, or use class labels with traditional classification setting (e.g., cross-entropy loss)? Thank you.

**Comment by LinB203** [comment]
Sorry for late reply. You can refer to [this](scripts/video_language/train_1.5_large.sh). We didn't add any tricks, just removed LoRA.

**Comment by aopolin-lv** [comment]
> Sorry for late reply. You can refer to [this](scripts/video_language/train_1.5_large.sh). We didn't add any tricks, just removed LoRA.

Hyperlink not found and please update. Thank you!

**Comment by LinB203** [comment]
> > Sorry for late reply. You can refer to [this](scripts/video_language/train_1.5_large.sh). We didn't add any tricks, just removed LoRA.
> 
> Hyperlink is not found and please update. Thank you!

Sorry, we have updated.
https://github.com/PKU-YuanGroup/LanguageBind/blob/main/scripts/video_language/train_1.5_large.sh

**Comment by aopolin-lv** [comment]
> > > Sorry for late reply. You can refer to [this](scripts/video_language/train_1.5_large.sh). We didn't add any tricks, just removed LoRA.
> > 
> > 
> > Hyperlink is not found and please update. Thank you!
> 
> Sorry, we update it. https://github.com/PKU-YuanGroup/LanguageBind/blob/main/scripts/video_language/train_1.5_large.sh

Thanks for your response!
