### ISSUE TITLE
Vision encoder version

### ISSUE THREAD

**Issue by JosephPai** [PKU-YuanGroup/LanguageBind#34]
Hi authors,

Thanks for releasing the code.
I noticed that you mentioned "Note that our image encoder is the same as OpenCLIP. Not as fine-tuned as other modalities."
I would like to know what is the exact version of CLIP weight are you using?

Thanks!

**Comment by LinB203** [comment]
https://huggingface.co/laion/CLIP-ViT-L-14-DataComp.XL-s13B-b90K
