### ISSUE TITLE
GPU sources

### ISSUE THREAD

**Issue by xiaoaoran** [PKU-YuanGroup/LanguageBind#4]
Thanks for the job!

May I know how many GPU sources you used to train the foundation model?

**Comment by LinB203** [comment]
You can check GPU sources by this [line](https://github.com/PKU-YuanGroup/LanguageBind/blob/main/scripts/video_language/train.sh#L4).
Just 8 V100s for depth and infrared, 16 V100 for video and audio. If you use gradient accumulation, then 8 V100s would be fine for video and audio.

**Comment by xiaoaoran** [comment]
Thanks for the answer!
