### ISSUE TITLE
关于数据集的一些问题

### ISSUE THREAD

**Issue by XiaoZong0** [PKU-YuanGroup/LanguageBind#57]
根据作者的链接下载的数据集，为什么和作者的数据集不一样啊？总是缺点什么。另外为什么数据集只能是json和tar格式啊？
if args.do_train:
        if args.train_data.endswith(".json"):
            data[f"{args.clip_type}_pt"] = get_VAT_dataset(args)
        elif args.train_data.endswith(".tar"):
            data[f"{args.clip_type}_pt"] = get_wds_dataset(args, is_train=True, epoch=epoch)
        else:
            raise NameError

有没有人在train的时候遇到同样的问题？

**Comment by Myrtles1203** [comment]
我也遇到了同样的问题，请问最后是如何解决的？
