### ISSUE TITLE
When will you release the dataset?

### ISSUE THREAD

**Issue by xiangchen-Z** [PKU-YuanGroup/LanguageBind#9]

**Comment by LinB203** [comment]
Thank you for your interest in our work. We will release the dataset after publication.

**Comment by LinB203** [comment]
We are in the process of uploading thermal and depth data on [Hugging Face](https://huggingface.co/datasets/LanguageBind/VIDAL-Depth-Thermal) and expect the whole process to last 1-2 months.

**Comment by aopolin-lv** [comment]
> We are in the process of uploading thermal and depth data on [Hugging Face](https://huggingface.co/datasets/LanguageBind/VIDAL-Depth-Thermal) and expect the whole process to last 1-2 months.

Hello, congratulation for accpetance by ICLR2024! Is the 20T data all for training? Could you provide more details about how to use the data? And now there is about 20 gigabytes of files uploaded on huggingface. When will the upload be completed?
